;; Tox is a generic virtualenv management to run tests in different configurations.

[tox]
skipsdist = True
envlist = {py35,py36,py37,py38}-django111-{pil,imagemagick,graphicsmagick,redis,dynamodb,wand,pgmagick,dbm,vipsthumbnail}
          {py35,py36,py37,py38}-django22-{pil,imagemagick,graphicsmagick,redis,dynamodb,wand,pgmagick,dbm,vipsthumbnail}
          {py36,py37,py38}-django30-{pil,imagemagick,graphicsmagick,redis,dynamodb,wand,pgmagick,dbm,vipsthumbnail}

[testenv]
changedir = {toxinidir}/tests
deps = pytest
       pytest-cov
       coverage
       pytest-django
       Pillow
       redis: redis
       dynamodb: boto
       pgmagick: pgmagick
       wand: wand
       django111: Django>=1.11,<2.0
       django22: Django>=2.2,<3.0
       django30: Django>=3.0,<3.1

setenv = PYTHONPATH = {toxinidir}:{toxinidir}
         pil: DJANGO_SETTINGS_MODULE=tests.settings.pil
         imagemagick: DJANGO_SETTINGS_MODULE=tests.settings.imagemagick
         graphicsmagick: DJANGO_SETTINGS_MODULE=tests.settings.graphicsmagick
         vipsthumbnail: DJANGO_SETTINGS_MODULE=tests.settings.vipsthumbnail
         redis: DJANGO_SETTINGS_MODULE=tests.settings.redis
         dynamodb: DJANGO_SETTINGS_MODULE=tests.settings.dynamodb
         wand: DJANGO_SETTINGS_MODULE=tests.settings.wand
         pgmagick: DJANGO_SETTINGS_MODULE=tests.settings.pgmagick
         dbm: DJANGO_SETTINGS_MODULE=tests.settings.dbm

commands = py.test -rw --cov-config ../setup.cfg --cov sorl

[testenv:flake8]
changedir = {toxinidir}
skip_install = True
deps =
  flake8
  flake8-bugbear
  # flake8-import-order
commands = flake8 --show-source sorl/
